apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloJava.name }}
spec:
  type: {{ .Values.helloJava.service.type }}
  ports:
    - port: {{ .Values.helloJava.service.port }}
      targetPort: {{ .Values.helloJava.service.port }}
      protocol: TCP
      name: {{ .Values.helloJava.name }}
      {{- if eq .Values.helloJava.service.type "NodePort" }}
      nodePort: {{ .Values.helloJava.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.helloJava.name }}